### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by maximuml** [HDCoding/hinstaller#1]
Ubintu 18.04 lts, fresh install and got this error

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Haitou\Classes\Process::__construct() must be an instance of Symfony\Component\Console\Style\SymfonyStyle, null given, called in /home/ubuntu/hinstaller/src/Commands/InstallCommand.php on line 40 and defined in /home/ubuntu/hinstaller/src/Classes/Process.php:15
Stack trace:                                                                 #0 /home/ubuntu/hinstaller/src/Commands/InstallCommand.php(40): Haitou\Classes\Process->__construct(NULL)                                                 #1 /home/ubuntu/hinstaller/artisan(18): Haitou\Commands\InstallCommand->__construct()
#2 {main}                                                                      thrown in /home/ubuntu/hinstaller/src/Classes/Process.php on line 15  `

And composer installation need to be updated
`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"`

Thanks

**Comment by monill** [comment]
Hi @maximuml 
Sorry for the delay
Last time used was in December/2019
Now stopped to working, I will create a visual installer later
I have updated the readme too

Sorry for the inconvenient
