### ISSUE TITLE
Automated Installer hinstaller

### ISSUE THREAD

**Issue by Serialc0de** [HDCoding/hinstaller#2]
Instalando: *Composer*

Installer corrupt
Could not open input file: composer-setup.php
PHP Warning:  unlink(composer-setup.php): No such file or directory in Command line code on line 1

  Instalando: Pacotes do Composer
 De permissao de execucao ao arquivo via 'chmod +x install.sh'
 Erro: Falha ao instalar Pacotes do Composer!
 Por favor, tente re-executar o script via 'bash ./install.sh' como root

**Comment by monill** [comment]
Hi @Serialc0de 
Sorry for the delay
Last time used was in December/2019
Now stopped to working, I will create a visual installer later
I have updated the readme too

Sorry for the inconvenient
